name: Robot Automation Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  api-tests:
    runs-on: ubuntu-latest

    env:
      JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
      JIRA_PROJECT_KEY: ${{ secrets.JIRA_PROJECT_KEY }}
      JIRA_API_EMAIL: ${{ secrets.JIRA_API_EMAIL }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      AUTH_HEADER_B64: ${{ secrets.AUTH_HEADER_B64 }}
      JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}
      PLAYWRIGHT_HEADLESS: ${{ secrets.PLAYWRIGHT_HEADLESS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install robotframework
          pip install RESTLibrary
          pip install requests
          pip install robotframework-jsonlibrary

      - name: Run API tests
        run: |
          robot \
            --output output_api.xml \
            --log log_api.html \
            --report report_api.html \
            tests/api

      - name: Upload Robot Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: robot-api-reports
          path: |
            output_api.xml
            log_api.html
            report_api.html
